### ISSUE TITLE
Highlighting Course Conflicts Not Working As Expected

### ISSUE THREAD

**Issue by doprz** [doprz/UT-Registration-Planner#7]
## Issue
Highlighting course conflicts when a user adds the course to their course list only highlights and marks certain courses as having a course conflict.

### Works
![image](https://user-images.githubusercontent.com/52579214/172952519-af02e764-1369-4230-aff4-9e80b5f55f92.png)

### Doesn't Work
![image](https://user-images.githubusercontent.com/52579214/172952718-b7815229-cb39-4a9e-aee6-8213fea62a71.png)

**Comment by DiegoPerez1441** [comment]
It seems that the issue lies in the `convertDTTo48HI` function when converting a time in 12-hour format to a 48 interval value, but more specifically when the time is in pm.

## Current Code
``` javascript
const convertDTTo48HI = (dt_obj) => {

    let hour = dt_obj.time.split(/:/)[0]
    let minute = dt_obj.time.split(/:/)[1]

    let val = 0

    // [Note]: Check lower and uppercase
    if (dt_obj.timeOfDay == "a.m.") {
        val = Number(hour) * 2
        val += (Number(minute) == 30) ? 1 : 0
    } else if (dt_obj.timeOfDay == "p.m.") {
        val = Number(hour) * 2
        val += (Number(minute) == 30) ? 1 : 0
        val += 24
    } else {
        // Catch errors
        console.warn("Error in converting DT to 48 hour inverval.")
    }

    return val
}
```

## Examples
12:00 p.m. (noon) should return 24, however it returns 48
11:00 a.m. works as expected and returns 22

**Comment by DiegoPerez1441** [comment]
## Possible solution
1. Convert the current time from a 12-hour to 24-hour format.
2. Convert the 24-hour formatted time into a 0-48 interval value.
